spring:
  cloud:
    gateway:
      routes:
        - id: short-link-admin-aggregation
          uri: lb://short-link-aggregation/api/abitoflink/admin/**
          predicates:
            - Path=/api/abitoflink/admin/**
          filters:
            - name: TokenValidate
              args:
                whitePathList:
                  - /api/abitoflink/admin/v1/user/login
                  - /api/abitoflink/admin/v1/user/is-username-available

        - id: short-link-project-aggregation
          uri: lb://short-link-aggregation/api/abitoflink/**
          predicates:
            - Path=/api/abitoflink/**
          filters:
            - name: TokenValidate